# Configuración de SonarQube Cloud

sonar.organization=erickkrv
sonar.projectKey=erickkrv_LAB-06-INGSOFTWAREII
sonar.projectName=Sistema de Inventarios y Ventas - API Backend
sonar.projectVersion=1.0

# Fuentes y exclusiones
sonar.sources=.
sonar.exclusions=tests/**,**/__pycache__/**,*.md,setup_project.py,add_tests.py

# Configuración de tests y cobertura
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
